export const API_ERROR_CODES = {
    ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
    ARTICLE_ALREADY_EXISTS: 'ARTICLE_ALREADY_EXISTS',
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    TAG_NOT_FOUND: 'TAG_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
    EMBEDDING_ERROR: 'EMBEDDING_ERROR',
} as const;

export const DEFAULT_PAGINATION = {
    PAGE: 1,
    PAGE_SIZE: 20,
} as const;

export const MAX_PAGINATION_SIZE = 100;
