import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ref } from '../src/reference';
import { type ThemeShape, tokenSchema } from '../src/schema';
import { themes } from '../src/themes';
import { flatten, toCssVar } from '../src/utils';

const distDir = resolve(__dirname, '..', 'dist');
mkdirSync(distDir, { recursive: true });

for (const [name, theme] of Object.entries(themes)) {
    const result = tokenSchema.safeParse(theme);
    if (!result.success) {
        console.error(`Theme "${name}" failed validation:`);
        console.error(result.error.format());
        process.exit(1);
    }
}

const lightFlat = flatten(themes.light);
const darkFlat = flatten(themes.dark);

const cssBody = (entries: Record<string, string>): string =>
    Object.entries(entries)
        .map(([path, value]) => `  ${toCssVar(path)}: ${value};`)
        .join('\n');

const cssOut = `/* Generated by @my-km/design-tokens. Do not edit by hand. */\n\n:root,\n[data-theme="light"] {\n${cssBody(lightFlat)}\n}\n\n[data-theme="dark"] {\n${cssBody(darkFlat)}\n}\n`;
writeFileSync(resolve(distDir, 'tokens.css'), cssOut);

const jsonOut = {
    reference: ref,
    themes: themes as Record<string, ThemeShape>,
};
writeFileSync(resolve(distDir, 'tokens.json'), `${JSON.stringify(jsonOut, null, 2)}\n`);

const cssVarTree = (input: unknown, prefix: string[] = []): unknown => {
    if (typeof input === 'string') {
        return `var(${toCssVar(prefix.join('.'))})`;
    }
    if (input && typeof input === 'object') {
        const out: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(input as Record<string, unknown>)) {
            out[key] = cssVarTree(value, [...prefix, key]);
        }
        return out;
    }
    return input;
};

const tokensVarTree = cssVarTree(themes.light);
const tsOut = `// Generated by @my-km/design-tokens. Do not edit by hand.\n\nexport const tokens = ${JSON.stringify(tokensVarTree, null, 2)} as const;\n\nexport type Tokens = typeof tokens;\n`;
writeFileSync(resolve(distDir, 'tokens.ts'), tsOut);

const dtsOut = `// Generated by @my-km/design-tokens. Do not edit by hand.\n\nexport declare const tokens: ${typeAnnotation(tokensVarTree)};\nexport type Tokens = typeof tokens;\n`;
writeFileSync(resolve(distDir, 'tokens.d.ts'), dtsOut);

function typeAnnotation(node: unknown): string {
    if (typeof node === 'string') return 'string';
    if (node && typeof node === 'object') {
        const entries = Object.entries(node as Record<string, unknown>)
            .map(([key, value]) => `  readonly ${JSON.stringify(key)}: ${typeAnnotation(value)};`)
            .join('\n');
        return `{\n${entries}\n}`;
    }
    return 'unknown';
}

console.log(`✓ Wrote ${Object.keys(lightFlat).length} tokens × 2 themes to ${distDir}`);
